# Generated by Django 3.2 on 2022-05-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('imdb_id', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=500)),
            ],
        ),
    ]
